Repository marlinprotocol/interface-v2, pull requests merged in 2024-03, with the labels that each got.

#177 fix: OPs are not being removed wile removing CP Url
  src/lib/page-components/oyster/operator/OysterOperatorRegisterPage.svelte
Labels: bug

#166 Integration tests
  .env.example
  .gitignore
  package-lock.json
  package.json
  playwright.config.ts
  src/lib/chains/arbSepolia.ts
  src/lib/components/header/sub-components/DisconnectWalletModal.svelte
  src/lib/page-components/oyster/inventory/modals/JobDetailsModal.svelte
  src/lib/page-components/oyster/operator/OysterOperatorRegisterPage.svelte
  test/docs.md
  test/e2e/walletConected/claim.spec.ts
  test/e2e/walletConected/deployAJob.spec.ts
  test/e2e/walletConected/inventory.spec.ts
  test/e2e/walletConected/operatorRegistration.spec.ts
  test/e2e/walletNotConnected/basic.spec.ts
  test/e2e/walletNotConnected/inventory.spec.ts
  test/e2e/walletNotConnected/marketplace.spec.ts
  test/e2e/walletNotConnected/oyster.spec.ts
  test/helpers/common.ts
  test/helpers/marketplace.ts
  test/helpers/metamask.ts
  test/wallet-setup/basic.setup.ts
  test/wallet-setup/connected.setup.ts
Labels: testing

#176 PR to improve API calls and create uniformity
  src/lib/chains/polygon.ts
  src/lib/components/header/sub-components/ChainSwitcher.svelte
  src/lib/components/header/sub-components/HeaderConnectWallet.svelte
  src/lib/data-stores/oysterStore.ts
  src/lib/data-stores/walletProviderStore.ts
  src/lib/page-components/bridge/history/MPondToPondHistoryData.svelte
  src/lib/page-components/bridge/history/PondToMPondHistoryData.svelte
  src/lib/utils/helpers/oysterHelpers.ts
  src/routes/bridge/+layout.svelte
  src/routes/bridge/+page.svelte
  src/routes/bridge/mPondToPondHistory/+page.svelte
  src/routes/bridge/pondToMPondHistory/+page.svelte
  src/routes/oyster/+layout.svelte
  src/routes/oyster/inventory/+layout.svelte
  src/routes/oyster/operator/+page.svelte
  src/routes/oyster/operator/jobs/+layout.svelte
  src/routes/relay/receiver/rewards/+page.svelte
  src/routes/relay/receiver/staking/+page.svelte
Labels: bug

#180 PR to add better syntax highlighting to dotenv snippets and run prettier on the codebase
  .env.example
  README.md
  package.json
  playwright.config.ts
  src/app.html
  src/lib/atoms/cards/InputCard.dom.spec.ts
  src/lib/atoms/cards/InputCard.svelte
  src/lib/atoms/icons/Icon.dom.spec.ts
  src/lib/atoms/icons/Icon.svelte
  src/lib/atoms/images/Image.dom.spec.ts
  src/lib/atoms/pop-over/PopOver.dom.spec.ts
  src/lib/atoms/pop-over/PopOver.svelte
  src/lib/atoms/table/Table.svelte
  src/lib/atoms/texts/Text.dom.spec.ts
  src/lib/atoms/texts/Text.svelte
  src/lib/components/buttons/CollapseButton.svelte
  src/lib/components/cards/ErrorTextCard.dom.spec.ts
  src/lib/components/header/sub-components/ConnectWalletButton.svelte
  src/lib/components/header/sub-components/DisconnectWalletButton.dom.spec.ts
  src/lib/components/header/sub-components/DisconnectWalletButton.svelte
  src/lib/components/header/sub-components/DisconnectWalletModal.svelte
  src/lib/components/icons/TxnIcon.dom.spec.ts
  src/lib/components/inputs/AmountInput.dom.spec.ts
  src/lib/components/loading/Loading.dom.spec.ts
  src/lib/components/modals/ApproveAndConfirmModal.svelte
  src/lib/components/pagination/Pagination.dom.spec.ts
  src/lib/components/pagination/Pagination.svelte
  src/lib/data-stores/mock-data-stores/mockStores.ts
  src/lib/page-components/bridge/MPondTopond.svelte
  src/lib/page-components/bridge/modals/MPondConversionCycleModal.svelte
  src/lib/page-components/bridge/modals/MPondConversionHistoryModal.svelte
  src/lib/page-components/oyster/inventory/modals/JobDetailsModal.svelte
  src/lib/page-components/oyster/inventory/modals/WithdrawFundsFromJobModal.svelte
  src/lib/page-components/oyster/operator/OysterOperatorRegisterPage.svelte
  src/lib/page-components/oyster/sub-components/BandwidthSelector.svelte
  src/lib/page-components/oyster/sub-components/MetadetailsForNewOrder.svelte
  src/lib/page-components/receiver-staking/StakeModal.svelte
  src/lib/page-components/receiver-staking/UnstakeModal.svelte
  src/lib/utils/README.md
  src/routes/+layout.svelte
  test/README.md
  test/docs.md
  test/e2e/walletConected/claim.spec.ts
  test/e2e/walletConected/deployAJob.spec.ts
  test/e2e/walletConected/inventory.spec.ts
  test/e2e/walletConected/operatorRegistration.spec.ts
  test/e2e/walletNotConnected/basic.spec.ts
  test/e2e/walletNotConnected/inventory.spec.ts
  test/e2e/walletNotConnected/marketplace.spec.ts
  test/e2e/walletNotConnected/oyster.spec.ts
  test/helpers/common.ts
  test/helpers/marketplace.ts
  test/helpers/metamask.ts
  test/wallet-setup/basic.setup.ts
  test/wallet-setup/connected.setup.ts
Labels: enhancement

#178 test: Added OPs table Unit Test cases
  .env.example
  src/lib/page-components/oyster/operator/OysterOperatorRegisterPage.spec.ts
  src/lib/page-components/oyster/operator/__snapshots__/OysterOperatorRegisterPage.spec.ts.snap
  test/README.md
Labels: testing

#189 PR to fix create order flow bugs
  src/lib/data-stores/walletProviderStore.ts
  src/lib/page-components/oyster/inventory/modals/CreateOrderModal.svelte
  src/lib/page-components/oyster/sub-components/BandwidthSelector.svelte
  src/lib/utils/services/oysterServices.ts
Labels: bug

#188 PR to add in functionality to update enclave url
  src/lib/controllers/contract/oyster.ts
  src/lib/data-stores/oysterStore.ts
  src/lib/page-components/oyster/inventory/OysterInventoryTableRow.svelte
  src/lib/page-components/oyster/inventory/modals/UpdateEnclaveUrlModal.svelte
  src/lib/utils/abis/oysterMarket.ts
  src/lib/utils/constants/messages.ts
  src/lib/utils/services/oysterServices.ts
Labels: enhancement
