Repository marlinprotocol/interface-v2, pull requests merged in 2024-06, with the labels that each got.

#367 fix: added hyle logo
  src/lib/components/images/staticImages.ts
  src/lib/page-components/ecosystem/EcosystemDashboard.svelte
  static/images/hyle.svg
Labels: enhancement

#368 Update subgraphs and port bridge subgraph calls to rpc
  .env.example
  src/lib/chains/arbOne.ts
  src/lib/chains/arbSepolia.ts
  src/lib/chains/linea.ts
  src/lib/chains/lineaGoerli.ts
  src/lib/chains/polygon.ts
  src/lib/controllers/contract/bridge.ts
  src/lib/controllers/contract/usdc.ts
  src/lib/data-stores/toastStore.ts
  src/routes/bridge/+layout.svelte
Labels: enhancement

#371 oyster market place update
  src/lib/page-components/oyster/marketplace/OysterMarketplaceFilters.svelte
  src/lib/page-components/oyster/marketplace/OysterMarketplacePage.svelte
  src/lib/utils/helpers/oysterHelper.test.ts
  src/lib/utils/helpers/oysterHelpers.ts
Labels: bug

#372 Tests fix: add funds to job using credits
  src/lib/page-components/oyster/inventory/modals/AddFundsToJobModal.svelte
  test/e2e/walletConected/credits.spec.ts
  test/helpers/inventory.ts
Labels: testing

#373 fix: some reported bug
  src/lib/components/header/sub-components/ChainSwitcher.svelte
  src/lib/page-components/oyster/marketplace/OysterMarketplacePage.svelte
  src/routes/oyster/+layout.svelte
Labels: bug

#375 fix: Unwanted err shown onchange of chain
  src/lib/controllers/walletController.ts
Labels: bug

#376 fix: some structural changes
  src/lib/page-components/kalypso/DashboardHeader.svelte
  src/lib/page-components/kalypso/KalypsoDashboard.svelte
  src/lib/page-components/kalypso/RegisteredOverview.svelte
Labels: enhancement

#377 feat: overview UI
  src/lib/atoms/cards/ContainerCard.svelte
  src/lib/page-components/kalypso/KalypsoDashboard.svelte
  src/lib/page-components/kalypso/RegisteredOverview.svelte
  src/lib/page-components/kalypso/modals/KalypsoRegisterModal.svelte
  src/lib/page-components/kalypso/modals/UpdateRewardAddModal.svelte
Labels: enhancement

#378 feat: stake & compute UI
  src/lib/data-stores/kalypsoStore.ts
  src/lib/page-components/kalypso/KalypsoDashboard.svelte
  src/lib/page-components/kalypso/ManageCompute.svelte
  src/lib/page-components/kalypso/ManageStake.svelte
  src/lib/page-components/kalypso/RegisteredOverview.svelte
  src/lib/types/storeTypes.ts
  src/lib/utils/constants/storeDefaults.ts
Labels: enhancement

#379 fix gap between second input suffix and balance text bridge
  src/lib/components/inputs/AmountInputWithMaxButton.svelte
  src/lib/components/inputs/__snapshots__/AmountInputWithMaxButton.dom.spec.ts.snap
Labels: bug

#380 move toasts to bottom right and updated their animation
  src/lib/atoms/toast/Toast.svelte
  src/lib/data-stores/toastStore.ts
Labels: enhancement

#382 update arb one rpc
  src/lib/chains/arbOne.ts
Labels: bug

#383 update stop job modal to show "CREDITS"
  src/lib/page-components/oyster/sub-components/StopModalContent.svelte
Labels: enhancement

#384 fix showing credit toggle when wallet not whitelisted
  src/lib/controllers/subgraphController.ts
  src/lib/data-stores/oysterStore.ts
  src/lib/page-components/oyster/inventory/modals/CreateOrderModal.svelte
  src/routes/oyster/+layout.svelte
Labels: bug

#386 ecosys ui fix
  src/lib/page-components/ecosystem/EcosystemDashboard.svelte
Labels: enhancement

#387 fixed ui bugs
  src/lib/components/texts/TextInputCard.svelte
  src/lib/components/texts/__snapshots__/Texts.dom.spec.ts.snap
  src/lib/page-components/oyster/inventory/OysterInventoryPage.svelte
Labels: bug

#388 add kalypso dashboard to marlin hub
  src/lib/atoms/cards/ContainerCard.svelte
  src/lib/atoms/componentClasses.ts
  src/lib/chains/arbGoerli.ts
  src/lib/chains/arbOne.ts
  src/lib/chains/arbSepolia.ts
  src/lib/chains/ethereum.ts
  src/lib/chains/linea.ts
  src/lib/chains/lineaGoerli.ts
  src/lib/chains/polygon.ts
  src/lib/components/empty-state/EmptyCard.svelte
  src/lib/components/inputs/AmountInput.svelte
  src/lib/components/inputs/AmountInputWithMaxButton.svelte
  src/lib/components/inputs/AmountInputWithTitle.svelte
  src/lib/components/inputs/__snapshots__/AmountInputWithTitle.dom.spec.ts.snap
  src/lib/controllers/contract/kalypso.ts
  src/lib/controllers/contract/token.ts
  src/lib/controllers/contract/usdc.ts
  src/lib/data-stores/kalypsoStore.ts
  src/lib/data-stores/walletProviderStore.ts
  src/lib/environments/environment.dev.ts
  src/lib/environments/environment.mainnet.ts
  src/lib/page-components/dashboard/MarlinHubDashboard.svelte
  src/lib/page-components/ecosystem/EcosystemDashboard.svelte
  src/lib/page-components/kalypso/AddStake.svelte
  src/lib/page-components/kalypso/DashboardHeader.svelte
  src/lib/page-components/kalypso/DecreaseCompute.svelte
  src/lib/page-components/kalypso/IncreaseCompute.svelte
  src/lib/page-components/kalypso/KalypsoDashboard.svelte
  src/lib/page-components/kalypso/ManageCompute.svelte
  src/lib/page-components/kalypso/ManageStake.svelte
  src/lib/page-components/kalypso/RegisteredOverview.svelte
  src/lib/page-components/kalypso/WithdrawStake.svelte
  src/lib/page-components/kalypso/modals/KalypsoRegisterModal.svelte
  src/lib/page-components/kalypso/modals/KalypsoUnregisterModal.svelte
  src/lib/page-components/kalypso/modals/UpdateRewardAddModal.svelte
  src/lib/page-components/oyster/dashboard/OysterDashboardPage.svelte
  src/lib/page-components/oyster/inventory/modals/AddFundsToJobModal.svelte
  src/lib/page-components/oyster/inventory/modals/CreateOrderModal.svelte
  src/lib/page-components/oyster/sub-components/AddFundsToJob.svelte
  src/lib/types/environmentTypes.ts
  src/lib/types/storeTypes.ts
  src/lib/utils/abis/kalypso.ts
  src/lib/utils/constants/kalypsoConstants.ts
  src/lib/utils/constants/messages.ts
  src/lib/utils/constants/storeDefaults.ts
  src/lib/utils/helpers/commonHelper.test.ts
  src/lib/utils/helpers/commonHelper.ts
  src/lib/utils/helpers/conversionHelper.ts
  src/lib/utils/services/kalypsoServices.ts
  src/lib/utils/services/oysterServices.ts
  src/routes/bridge/+layout.svelte
  src/routes/kalypso/+layout.svelte
  src/routes/kalypso/+page.svelte
  src/routes/oyster/+layout.svelte
Labels: enhancement
