Repository marlinprotocol/interface-v2, pull requests merged in 2024-04, with the labels that each got.

#185 Tests chain
  src/lib/chains/arbGoerli.ts
  test/e2e/walletConected/chain.spec.ts
  test/e2e/walletConected/deployAJob.spec.ts
Labels: testing

#197 feat: added utility function for conditional class
  package-lock.json
  package.json
  src/lib/utils/helpers/commonHelper.ts
Labels: good first issue

#198 PR to update the redirect for new UI
  src/lib/components/v2/header/sub-components/SidebarLinksGroup.svelte
  src/lib/page-components/v2/dashboard/MarlinHubDashboard.svelte
  src/lib/utils/constants/v2/urls.ts
  src/routes/v2/+page.ts
  src/routes/v2/dashboard/+page.svelte
Labels: enhancement

#199 Layout for v2
  src/lib/components/v2/wrapper/PageWrapper.dom.spec.ts
  src/lib/components/v2/wrapper/PageWrapper.svelte
  src/lib/components/v2/wrapper/__snapshots__/PageWrapper.dom.spec.ts.snap
  src/routes/v2/+error.svelte
  src/routes/v2/bridge/+layout.svelte
  src/routes/v2/oyster/+layout.svelte
  src/routes/v2/relay/+layout.svelte
Labels: ui

#196 Sidebar with Fixed bottom buttons
  src/lib/components/images/staticImages.ts
  src/lib/components/v2/header/sub-components/MenuItem.svelte
  src/lib/components/v2/header/sub-components/SidebarLinksGroup.svelte
  src/lib/components/v2/sidebar/Sidebar.svelte
  src/lib/types/v2/navigation.ts
  src/lib/utils/constants/v2/navigation.ts
  static/images/blog.svg
  static/images/developerChatIcon.svg
  static/images/earth.svg
  static/images/lightModeLogo.svg
Labels: ui

#200 INTER-51: New UI Pagination component
  src/lib/components/images/staticImages.ts
  src/lib/components/v2/header/sub-components/SidebarLinksGroup.svelte
  src/lib/components/v2/pagination/Pagination.svelte
  static/images/arrowLeftSolid.svg
  static/images/arrowRightSolid.svg
Labels: ui

#202 INTER-47: Designed new UI Modal component
  src/lib/atoms/v2/buttons/Button.dom.spec.ts
  src/lib/atoms/v2/buttons/Button.svelte
  src/lib/atoms/v2/buttons/InfoButtonLink.dom.spec.ts
  src/lib/atoms/v2/buttons/InfoButtonLink.svelte
  src/lib/atoms/v2/buttons/TestButton.svelte
  src/lib/atoms/v2/buttons/__snapshots__/Button.dom.spec.ts.snap
  src/lib/atoms/v2/modals/Modal.dom.spec.ts
  src/lib/atoms/v2/modals/Modal.svelte
  src/lib/atoms/v2/modals/ModalButton.svelte
  src/lib/atoms/v2/modals/__snapshots__/Modal.dom.spec.ts.snap
  src/lib/components/images/staticImages.ts
  src/lib/components/v2/header/sub-components/DisconnectWalletModal.svelte
  static/images/SuccessIcon.svg
  static/images/alertRed.svg
  static/images/closeIcon.svg
  tailwind.config.cjs
Labels: ui

#201 Table Layout v2
  src/app.css
  src/lib/atoms/v2/buttons/Button.svelte
  src/lib/atoms/v2/cards/ContainerCard.dom.spec.ts
  src/lib/atoms/v2/cards/ContainerCard.svelte
  src/lib/atoms/v2/cards/InputCard.dom.spec.ts
  src/lib/atoms/v2/cards/InputCard.svelte
  src/lib/atoms/v2/cards/__snapshots__/InputCard.dom.spec.ts.snap
  src/lib/atoms/v2/componentClasses.ts
  src/lib/atoms/v2/modals/ModalButton.svelte
  src/lib/atoms/v2/table/Table.dom.spec.ts
  src/lib/atoms/v2/table/Table.svelte
  src/lib/atoms/v2/table/__snapshots__/Table.dom.spec.ts.snap
  src/lib/atoms/v2/tooltips/Tooltip.dom.spec.ts
  src/lib/atoms/v2/tooltips/Tooltip.svelte
  src/lib/atoms/v2/tooltips/TooltipIcon.dom.spec.ts
  src/lib/atoms/v2/tooltips/TooltipIcon.svelte
  src/lib/atoms/v2/tooltips/__snapshots__/Tooltip.dom.spec.ts.snap
  src/lib/atoms/v2/tooltips/__snapshots__/TooltipIcon.dom.spec.ts.snap
  src/lib/components/images/staticImages.ts
  src/lib/components/v2/buttons/BackButton.svelte
  src/lib/components/v2/buttons/CollapseButton.svelte
  src/lib/components/v2/buttons/MaxButton.svelte
  src/lib/components/v2/buttons/__snapshots__/buttons.dom.spec.ts.snap
  src/lib/components/v2/buttons/buttons.dom.spec.ts
  src/lib/components/v2/pagination/Pagination.svelte
  src/lib/components/v2/search/Country.dom.spec.ts
  src/lib/components/v2/search/Country.svelte
  src/lib/components/v2/search/SearchBar.dom.spec.ts
  src/lib/components/v2/search/SearchBar.svelte
  src/lib/components/v2/search/SearchWithSelect.dom.spec.ts
  src/lib/components/v2/search/SearchWithSelect.svelte
  src/lib/components/v2/search/__snapshots__/Country.dom.spec.ts.snap
  src/lib/components/v2/search/__snapshots__/SearchBar.dom.spec.ts.snap
  src/lib/components/v2/search/__snapshots__/SearchWithSelect.dom.spec.ts.snap
  src/lib/components/v2/select/Select.dom.spec.ts
  src/lib/components/v2/select/Select.svelte
  src/lib/components/v2/select/__snapshots__/Select.dom.spec.ts.snap
  src/lib/components/v2/texts/NameWithAddress.svelte
  src/lib/components/v2/texts/PageTitle.svelte
  src/lib/components/v2/texts/TableHeadingText.svelte
  src/lib/components/v2/texts/TextInputCard.svelte
  src/lib/components/v2/texts/Texts.dom.spec.ts
  src/lib/components/v2/texts/TxnHashText.svelte
  src/lib/components/v2/texts/__snapshots__/Texts.dom.spec.ts.snap
  src/lib/page-components/v2/oyster/inventory/OysterTableCommon.svelte
  src/lib/page-components/v2/oyster/marketplace/OysterMarketplaceFilters.svelte
  src/lib/page-components/v2/oyster/marketplace/OysterMarketplacePage.svelte
  src/lib/page-components/v2/oyster/marketplace/OysterMarketplaceTableRow.svelte
  src/lib/page-components/v2/oyster/marketplace/TableFilter.svelte
  src/lib/types/v2/componentTypes.ts
  src/lib/utils/constants/v2/oysterConstants.ts
  src/lib/utils/v2/helpers/componentHelper.ts
  src/routes/v2/+layout.svelte
  src/routes/v2/oyster/marketplace/+page.svelte
  static/images/alertV2Icon.svg
  static/images/chevronDownIcon.svg
  static/images/sortV2Icon.svg
  tailwind.config.cjs
Labels: ui

#203 INTER-55: New Toast component as per new UI
  src/lib/atoms/v2/toast/Toast.dom.spec.ts
  src/lib/atoms/v2/toast/Toast.svelte
  src/lib/atoms/v2/toast/__snapshots__/Toast.dom.spec.ts.snap
  src/lib/components/images/staticImages.ts
  src/lib/data-stores/v2/toastStore.ts
  src/lib/types/v2/componentTypes.ts
  src/lib/utils/v2/helpers/componentHelper.ts
  src/routes/v2/+layout.svelte
  static/images/toastErrorAlert.svg
  static/images/toastSuccessAlert.svg
  static/images/toastWarningAlert.svg
Labels: ui

#204 feat: added scroll UI & sidebar scroll issue
  src/app.css
  src/lib/components/v2/header/sub-components/SidebarLinksGroup.svelte
Labels: enhancement, ui

#207 PR to add in the new bridge UI
  src/lib/atoms/componentClasses.ts
  src/lib/atoms/v2/buttons/Button.svelte
  src/lib/atoms/v2/cards/InputCard.svelte
  src/lib/atoms/v2/componentClasses.ts
  src/lib/atoms/v2/tabs/Tab.svelte
  src/lib/atoms/v2/tabs/TabList.svelte
  src/lib/atoms/v2/tabs/TabPanel.svelte
  src/lib/atoms/v2/tabs/Tabs.dom.spec.ts
  src/lib/atoms/v2/tabs/Tabs.svelte
  src/lib/atoms/v2/tabs/__snapshots__/Tabs.dom.spec.ts.snap
  src/lib/atoms/v2/tabs/tabs.ts
  src/lib/components/images/staticImages.ts
  src/lib/components/v2/header/sub-components/ConnectWalletButton.svelte
  src/lib/components/v2/header/sub-components/SidebarLinksGroup.svelte
  src/lib/components/v2/inputs/AmountInput.dom.spec.ts
  src/lib/components/v2/inputs/AmountInput.svelte
  src/lib/components/v2/inputs/AmountInputWithMaxButton.dom.spec.ts
  src/lib/components/v2/inputs/AmountInputWithMaxButton.svelte
  src/lib/components/v2/inputs/AmountInputWithTitle.dom.spec.ts
  src/lib/components/v2/inputs/AmountInputWithTitle.svelte
  src/lib/components/v2/inputs/InputCardWithEndButton.dom.spec.ts
  src/lib/components/v2/inputs/InputCardWithEndButton.svelte
  src/lib/components/v2/inputs/TextInputWithEndButton.dom.spec.ts
  src/lib/components/v2/inputs/TextInputWithEndButton.svelte
  src/lib/components/v2/inputs/__snapshots__/AmountInput.dom.spec.ts.snap
  src/lib/components/v2/inputs/__snapshots__/AmountInputWithMaxButton.dom.spec.ts.snap
  src/lib/components/v2/inputs/__snapshots__/AmountInputWithTitle.dom.spec.ts.snap
  src/lib/components/v2/inputs/__snapshots__/InputCardWithEndButton.dom.spec.ts.snap
  src/lib/components/v2/inputs/__snapshots__/TextInputWithEndButton.dom.spec.ts.snap
  src/lib/components/wrapper/PageWrapper.svelte
  src/lib/page-components/v2/bridge/BridgeDashboard.svelte
  src/lib/page-components/v2/bridge/MPondTopond.svelte
  src/lib/page-components/v2/bridge/PondApproveConfirmModal.svelte
  src/lib/page-components/v2/bridge/PondToMPond.svelte
  src/lib/page-components/v2/bridge/buttons/MPondConversionCycleButton.svelte
  src/lib/page-components/v2/bridge/buttons/MPondConversionHistoryButton.svelte
  src/lib/page-components/v2/bridge/history/HistoryTableCommon.svelte
  src/lib/page-components/v2/bridge/history/MPondTableRow.svelte
  src/lib/page-components/v2/bridge/history/MPondToPondHistoryData.svelte
  src/lib/page-components/v2/bridge/history/PondToMPondHistoryData.svelte
  src/lib/page-components/v2/bridge/modals/MPondApproveConfirmModal.svelte
  src/lib/page-components/v2/bridge/modals/MPondConversionCycleModal.svelte
  src/lib/page-components/v2/bridge/modals/MPondConversionHistoryModal.svelte
  src/lib/page-components/v2/bridge/modals/MPondEligibleConvertModal.svelte
  src/lib/page-components/v2/bridge/modals/SuccessfulConversionModal.svelte
  src/lib/page-components/v2/bridge/sub-components/ConversionHistoryButton.svelte
  src/lib/page-components/v2/bridge/sub-components/HistoryBackButton.svelte
  src/lib/page-components/v2/bridge/sub-components/HistoryDataIconButton.svelte
  src/lib/page-components/v2/bridge/sub-components/TabPondMPond.svelte
  src/lib/types/v2/componentTypes.ts
  src/lib/utils/v2/helpers/componentHelper.ts
  src/routes/v2/+layout.svelte
  src/routes/v2/bridge/+layout.svelte
  src/routes/v2/bridge/+page.svelte
  static/images/arrowConversion.svg
  static/images/conversionIcon.svg
  tailwind.config.cjs
Labels: enhancement, ui

#205 INTER-57: New Tooltip UI
  src/lib/atoms/v2/tooltips/Tooltip.svelte
  src/lib/atoms/v2/tooltips/TooltipIcon.dom.spec.ts
  src/lib/atoms/v2/tooltips/TooltipIcon.svelte
  src/lib/atoms/v2/tooltips/__snapshots__/TooltipIcon.dom.spec.ts.snap
  src/lib/types/v2/componentTypes.ts
Labels: ui

#208 fix: Sidebar height issue
  src/lib/components/v2/header/sub-components/MenuItem.svelte
  src/lib/components/v2/header/sub-components/SidebarLinksGroup.svelte
  src/lib/components/v2/sidebar/Sidebar.svelte
  src/lib/data-stores/v2/navStore.ts
  src/routes/v2/+layout.svelte
Labels: bug, ui

#209 PR to update bridge modals to new UI and refactor markup
  src/lib/atoms/v2/modals/Modal.svelte
  src/lib/components/images/staticImages.ts
  src/lib/components/v2/modals/ApproveAndConfirmModal.dom.spec.ts
  src/lib/components/v2/modals/ApproveAndConfirmModal.svelte
  src/lib/components/v2/modals/Modal.dom.spec.ts
  src/lib/components/v2/sidebar/Sidebar.svelte
  src/lib/components/v2/wrapper/PageWrapper.svelte
  src/lib/page-components/v2/bridge/PondApproveConfirmModal.svelte
  src/lib/page-components/v2/bridge/PondToMPond.svelte
  src/lib/page-components/v2/bridge/modals/SuccessfulConversionModal.svelte
  src/routes/v2/+layout.svelte
  src/routes/v2/bridge/+layout.svelte
  static/images/checkmark.svg
  static/images/closeIcon.svg
  static/images/tick.svg
Labels: ui

#206 History Table v2
  src/lib/atoms/v2/table/Table.svelte
  src/lib/atoms/v2/tooltips/TooltipIcon.svelte
  src/lib/components/images/staticImages.ts
  src/lib/components/v2/table-cells/TableCells.dom.spec.ts
  src/lib/components/v2/table-cells/TableDataCell.svelte
  src/lib/components/v2/table-cells/TableDataWithButton.svelte
  src/lib/components/v2/table-cells/__snapshots__/TableCells.dom.spec.ts.snap
  src/lib/components/v2/texts/NameWithAddress.svelte
  src/lib/components/v2/texts/TableHeadingText.svelte
  src/lib/page-components/v2/bridge/buttons/MPondConversionCycleButton.svelte
  src/lib/page-components/v2/bridge/buttons/MPondConversionHistoryButton.svelte
  src/lib/page-components/v2/bridge/history/HistoryTableCommon.svelte
  src/lib/page-components/v2/bridge/history/MPondTableRow.svelte
  src/lib/page-components/v2/bridge/history/MPondToPondHistoryData.svelte
  src/lib/page-components/v2/bridge/history/PondToMPondHistoryData.svelte
  src/lib/page-components/v2/bridge/modals/MPondConversionCycleModal.svelte
  src/lib/page-components/v2/bridge/modals/MPondConversionHistoryModal.svelte
  src/lib/page-components/v2/bridge/modals/MPondEligibleConvertModal.svelte
  src/lib/page-components/v2/oyster/marketplace/OysterMarketplacePage.svelte
  src/lib/utils/constants/v2/bridgeConstants.ts
  src/routes/v2/+layout.svelte
  src/routes/v2/bridge/+layout.svelte
  src/routes/v2/bridge/mPondToPondHistory/+page.svelte
  src/routes/v2/bridge/pondToMPondHistory/+page.svelte
  src/routes/v2/oyster/+layout.svelte
  static/images/backV2Icon.svg
  static/images/cancelV2Icon.svg
  static/images/conversionCycleV2Icon.svg
  static/images/exchangeV2Icon.svg
  static/images/externalLinkV2Icon.svg
  static/images/historyV2Icon.svg
Labels: ui

#210 INTER-58: Inventory modals
  src/lib/atoms/v2/cards/InputCard.svelte
  src/lib/atoms/v2/modals/Modal.svelte
  src/lib/components/images/staticImages.ts
  src/lib/components/inputs/AmountInput.svelte
  src/lib/components/v2/inputs/AmountInputWithTitle.svelte
  src/lib/components/v2/texts/TextInputCard.svelte
  src/lib/page-components/v2/oyster/inventory/OysterInventoryHistoryPage.svelte
  src/lib/page-components/v2/oyster/inventory/OysterInventoryHistoryTableRow.svelte
  src/lib/page-components/v2/oyster/inventory/OysterInventoryPage.svelte
  src/lib/page-components/v2/oyster/inventory/OysterInventoryTableRow.svelte
  src/lib/page-components/v2/oyster/inventory/modals/AddFundsToJobModal.svelte
  src/lib/page-components/v2/oyster/inventory/modals/AmendRateModal.svelte
  src/lib/page-components/v2/oyster/inventory/modals/CreateOrderModal.svelte
  src/lib/page-components/v2/oyster/inventory/modals/JobDetailsModal.svelte
  src/lib/page-components/v2/oyster/inventory/modals/PastJobDetailsModal.svelte
  src/lib/page-components/v2/oyster/inventory/modals/StopJobModal.svelte
  src/lib/page-components/v2/oyster/inventory/modals/WithdrawFundsFromJobModal.svelte
  src/lib/page-components/v2/oyster/sub-components/AddFundsToJob.svelte
  src/lib/page-components/v2/oyster/sub-components/BandwidthSelector.svelte
  src/lib/page-components/v2/oyster/sub-components/InstancesTable.svelte
  src/lib/page-components/v2/oyster/sub-components/MetadetailsForNewOrder.svelte
  src/lib/page-components/v2/oyster/sub-components/PaymentHistoryTable.svelte
  src/lib/page-components/v2/oyster/sub-components/StopModalContent.svelte
  src/lib/types/v2/componentTypes.ts
  src/lib/utils/v2/helpers/componentHelper.ts
  src/routes/v2/+layout.svelte
  src/routes/v2/oyster/inventory/+page.svelte
  static/images/clockIcon.svg
  static/images/walletIconOyster.svg
Labels: ui

#216 PR to add margin around sidebar gray box and linear gradient around scrollable nav
  src/lib/components/v2/header/sub-components/SidebarLinksGroup.svelte
Labels: ui

#218 PR to add ecosystem page and route
  src/lib/components/images/staticImages.ts
  src/lib/page-components/v2/ecosystem/EcosystemDashboard.svelte
  src/routes/v2/ecosystem/+page.svelte
  static/images/AspectaLogo.png
  static/images/Avail-Logo-OnDark.3bbffcbf.png
  static/images/Brightlystakelogo.png
  static/images/ChorusOneLogo.png
  static/images/CradlesLogo.png
  static/images/DegoFinance.png
  static/images/EcholinkLogo.png
  static/images/GoSleepLogo.png
  static/images/HashkeyCloudLogo.png
  static/images/InfstonesLogo.png
  static/images/MidaswapLogo.png
  static/images/NodeEasyLogo.png
  static/images/PromLogo.png
  static/images/PublicAIDarkLogo.png
  static/images/ShanghaiJiaoTongUniversityLogo.png
  static/images/StafiLogo.png
  static/images/Staking4AllLogo.png
  static/images/T2T2Logo.png
  static/images/ankr-blue-logo.png
  static/images/p2p_logo_white.png
Labels: ui

#219 feat: added new styled input
  src/lib/atoms/v2/cards/InputCard.svelte
  src/lib/atoms/v2/modals/Modal.svelte
  src/lib/components/v2/buttons/CollapseButton.svelte
  src/lib/components/v2/inputs/AmountInput.svelte
  src/lib/components/v2/inputs/AmountInputWithTitle.svelte
  src/lib/components/v2/select/Select.svelte
  src/lib/page-components/v2/oyster/inventory/modals/AddFundsToJobModal.svelte
  src/lib/page-components/v2/oyster/sub-components/AddFundsToJob.svelte
Labels: ui

#220 fix: resolved toast for Bridge conversions
  src/lib/atoms/v2/modals/Modal.svelte
  src/lib/atoms/v2/toast/Toast.svelte
  src/lib/controllers/contract/bridge.ts
  src/lib/controllers/contract/oyster.ts
  src/lib/controllers/contract/oysterCredit.ts
  src/lib/controllers/contract/token.ts
  src/lib/page-components/oyster/inventory/modals/CreateOrderModal.svelte
  src/lib/page-components/oyster/operator/OysterOperatorRegisterPage.svelte
  src/lib/page-components/v2/oyster/inventory/modals/CreateOrderModal.svelte
  src/lib/page-components/v2/oyster/inventory/modals/JobDetailsModal.svelte
  src/lib/page-components/v2/oyster/inventory/modals/PastJobDetailsModal.svelte
  src/lib/page-components/v2/oyster/marketplace/OysterMarketplaceTableRow.svelte
  src/lib/page-components/v2/oyster/sub-components/PaymentHistoryTable.svelte
  src/lib/utils/constants/messages.ts
  src/lib/utils/constants/v2/oysterConstants.ts
  src/lib/utils/helpers/contractHelpers.ts
Labels: bug, enhancement

#224 PR to update sidebar nav links
  src/lib/components/v2/header/sub-components/MenuItem.svelte
  src/lib/components/v2/header/sub-components/SidebarLinksGroup.svelte
  src/lib/types/v2/navigation.ts
  src/lib/utils/constants/v2/navigation.ts
  src/lib/utils/constants/v2/urls.ts
Labels: enhancement

#225 fix: remove the chain name from disconnect wallet button
  src/lib/components/v2/header/sub-components/DisconnectWalletButton.svelte
Labels: enhancement

#226 fix: update the image for selected chain in the chain dropdown switcher
  src/lib/components/v2/header/sub-components/ChainSwitcher.svelte
Labels: enhancement

#228 PR to add modal and input fixes
  src/lib/atoms/v2/cards/InputCard.svelte
  src/lib/atoms/v2/modals/Modal.svelte
  src/lib/page-components/v2/oyster/inventory/modals/PastJobDetailsModal.svelte
  src/lib/page-components/v2/oyster/sub-components/PaymentHistoryTable.svelte
Labels: ui

#230 PR to add in modal fixes and other minor improvements
  src/lib/atoms/v2/modals/Modal.svelte
  src/lib/components/images/staticImages.ts
  src/lib/page-components/v2/bridge/MPondTopond.svelte
  src/lib/page-components/v2/bridge/PondToMPond.svelte
  src/lib/page-components/v2/bridge/buttons/MPondConversionCycleButton.svelte
  src/lib/page-components/v2/bridge/history/MPondTableRow.svelte
  src/lib/page-components/v2/bridge/history/MPondToPondHistoryData.svelte
  src/lib/page-components/v2/bridge/history/PondToMPondHistoryData.svelte
  src/lib/page-components/v2/bridge/modals/MPondConversionCycleModal.svelte
  src/lib/page-components/v2/bridge/modals/MPondEligibleConvertModal.svelte
  src/lib/types/bridgeComponentType.ts
  src/lib/utils/data-modifiers/subgraphModifier.ts
  static/images/calendar.svg
  static/images/checkmark-circle.svg
  static/images/clock.svg
  static/images/loading.svg
Labels: ui

#232 PR to update table layout in mpond conversion history and minor changes
  src/lib/components/v2/texts/TxnHashText.svelte
  src/lib/page-components/v2/bridge/history/MPondTableRow.svelte
  src/lib/page-components/v2/bridge/modals/MPondConversionHistoryModal.svelte
  src/lib/utils/constants/v2/bridgeConstants.ts
Labels: ui

#233 PR to make sidebar toggle controllable via js
  src/lib/components/v2/header/sub-components/SidebarLinksGroup.svelte
  src/lib/components/v2/sidebar/Sidebar.svelte
Labels: enhancement

#237 PR to add sidebar styling fixes
  src/lib/components/v2/header/sub-components/SidebarLinksGroup.svelte
  src/lib/components/v2/sidebar/Sidebar.svelte
Labels: bug, ui

#238 PR to add external link modal
  src/lib/components/v2/header/sub-components/SidebarLinksGroup.svelte
  src/lib/components/v2/modals/ExternalLinkConfirmationModal.svelte
Labels: ui

#239 PR to add minor tweaks to latest ui
  src/lib/page-components/v2/ecosystem/EcosystemDashboard.svelte
  static/images/ecosystemIcon.svg
  static/images/ecosystemIconBlue.svg
  static/images/settingsIcon.svg
  static/images/settingsIconBlue.svg
Labels: ui

#242 Oyster fixes
  src/lib/atoms/v2/componentClasses.ts
  src/lib/atoms/v2/modals/Modal.svelte
  src/lib/components/v2/inputs/AmountInputWithTitle.svelte
  src/lib/components/v2/search/SearchWithSelect.svelte
  src/lib/page-components/v2/oyster/inventory/modals/CreateOrderModal.svelte
  src/lib/page-components/v2/oyster/marketplace/OysterMarketplaceFilters.svelte
  src/lib/page-components/v2/oyster/sub-components/AddFundsToJob.svelte
  src/lib/page-components/v2/oyster/sub-components/BandwidthSelector.svelte
Labels: bug

#245 PR to add in fixes and updates to sidebar behaviour
  src/lib/components/v2/header/sub-components/SidebarLinksGroup.svelte
  src/lib/utils/constants/v2/navigation.ts
  src/lib/utils/constants/v2/urls.ts
Labels: bug, enhancement

#250 fix: PRECISIONS zero issue
  src/lib/page-components/v2/bridge/MPondTopond.svelte
  src/lib/page-components/v2/bridge/PondToMPond.svelte
Labels: bug, enhancement
