Repository marlinprotocol/interface-v2, pull requests merged in 2024-08, with the labels that each got.

#415 remove unused contracts, services and stores and ran prettier
  .github/actions/ci-setup/action.yml
  .github/workflows/test.yml
  README.md
  src/app.css
  src/app.html
  src/lib/chains/arbGoerli.ts
  src/lib/chains/arbOne.ts
  src/lib/chains/arbSepolia.ts
  src/lib/chains/ethereum.ts
  src/lib/chains/linea.ts
  src/lib/chains/lineaGoerli.ts
  src/lib/chains/polygon.ts
  src/lib/components/header/sub-components/ChainSwitcher.svelte
  src/lib/controllers/contract/receiverRewards.ts
  src/lib/controllers/contract/receiverStaking.ts
  src/lib/controllers/subgraphController.ts
  src/lib/controllers/walletController.ts
  src/lib/data-stores/epochCycleStore.ts
  src/lib/data-stores/receiverRewardsStore.ts
  src/lib/data-stores/receiverStakingStore.test.ts
  src/lib/data-stores/receiverStakingStore.ts
  src/lib/page-components/oyster/dashboard/OysterDashboardPage.svelte
  src/lib/page-components/oyster/sub-components/MetadetailsForNewOrder.svelte
  src/lib/types/storeTypes.ts
  src/lib/utils/abis/clusterRegistry.ts
  src/lib/utils/abis/mpond.ts
  src/lib/utils/abis/receiverStaking.ts
  src/lib/utils/abis/rewardDelegators.ts
  src/lib/utils/abis/stakeManager.ts
  src/lib/utils/constants/storeDefaults.ts
  src/lib/utils/services/receiverRewardServices.ts
  src/routes/+layout.svelte
  test/README.md
Labels: refactor

#419 fix: scroll fix inside a continer
  src/lib/components/texts/TextInputCard.svelte
  src/lib/page-components/oyster/inventory/modals/JobDetailsModal.svelte
Labels: enhancement

#422 add codeowners file
  .github/CODEOWNERS
Labels: github

#423 Coverage increase: subgraph modifiers and wallet provider store
  src/lib/data-stores/walletProviderStore.test.ts
  src/lib/utils/data-modifiers/subgraphModifier.ts
  src/lib/utils/data-modifiers/subgraphModifiers.test.ts
Labels: enhancement

#427 add gh action for better PRs
  .github/workflows/sizeup.yml
  .github/workflows/sizeup/config.yaml
Labels: github, sizeup/m

#428 update prod node env key from arb_mainnet -> mainnet
  README.md
  src/lib/data-stores/environment.ts
  src/lib/types/environmentTypes.ts
Labels: refactor, sizeup/s

#429 add codeql for code scanning in github ci
  .github/workflows/codeql.yml
Labels: github, sizeup/m
