Repository marlinprotocol/interface-v2, pull requests merged in 2024-07, with the labels that each got.

#390 Souvik/messages refactor
  src/lib/atoms/toast/Toast.svelte
  src/lib/controllers/contract/bridge.ts
  src/lib/controllers/contract/kalypso.ts
  src/lib/controllers/contract/oyster.ts
  src/lib/controllers/contract/oysterCredit.ts
  src/lib/controllers/contract/receiverRewards.ts
  src/lib/controllers/contract/receiverStaking.ts
  src/lib/controllers/contract/token.ts
  src/lib/data-stores/toastStore.ts
  src/lib/types/componentTypes.ts
  src/lib/utils/constants/messages.ts
  src/lib/utils/helpers/contractHelpers.ts
Labels: refactor

#392 update bridge and oyster credit subgraphs for arb sepolia
  src/lib/chains/arbSepolia.ts
Labels: enhancement

#389 basic UI setup for dark theme
  src/app.css
  src/lib/atoms/componentClasses.ts
  src/lib/atoms/modals/Modal.svelte
  src/lib/atoms/modals/__snapshots__/Modal.dom.spec.ts.snap
  src/lib/atoms/table/__snapshots__/Table.dom.spec.ts.snap
  src/lib/components/header/Header.svelte
  src/lib/components/header/sub-components/DisconnectWalletButton.svelte
  src/lib/components/header/sub-components/SidebarLinksGroup.svelte
  src/lib/components/header/sub-components/__snapshots__/ChainSwitcher.dom.spec.ts.snap
  src/lib/components/header/sub-components/__snapshots__/DisconnectWalletButton.dom.spec.ts.snap
  src/lib/components/header/sub-components/__snapshots__/DisconnectWalletModal.dom.spec.ts.snap
  src/lib/components/header/sub-components/__snapshots__/HeaderConnectWallet.dom.spec.ts.snap
  src/lib/components/header/sub-components/__snapshots__/HeaderLinksGroup.dom.spec.ts.snap
  src/lib/components/header/sub-components/__snapshots__/HeaderSubComponents.dom.spec.ts.snap
  src/lib/components/inputs/AmountInputWithMaxButton.svelte
  src/lib/components/inputs/AmountInputWithTitle.svelte
  src/lib/components/inputs/InputCardWithEndButton.svelte
  src/lib/components/inputs/TextInputWithEndButton.svelte
  src/lib/components/inputs/__snapshots__/AmountInputWithMaxButton.dom.spec.ts.snap
  src/lib/components/inputs/__snapshots__/AmountInputWithTitle.dom.spec.ts.snap
  src/lib/components/inputs/__snapshots__/TextInputWithEndButton.dom.spec.ts.snap
  src/lib/components/modals/ApproveAndConfirmModal.svelte
  src/lib/components/modals/__snapshots__/ApproveAndConfirmModal.dom.spec.ts.snap
  src/lib/components/modals/__snapshots__/Modal.dom.spec.ts.snap
  src/lib/components/prompts/__snapshots__/Prompts.dom.spec.ts.snap
  src/lib/components/search/SearchBar.svelte
  src/lib/components/search/SearchWithSelect.svelte
  src/lib/components/search/__snapshots__/SearchBar.dom.spec.ts.snap
  src/lib/components/search/__snapshots__/SearchWithSelect.dom.spec.ts.snap
  src/lib/components/sidebar/Sidebar.svelte
  src/lib/components/texts/PageTitle.svelte
  src/lib/components/texts/TableHeadingText.svelte
  src/lib/components/texts/TextInputCard.svelte
  src/lib/components/texts/__snapshots__/Texts.dom.spec.ts.snap
  src/lib/page-components/bridge/modals/MPondConversionCycleModal.svelte
  src/lib/page-components/dashboard/MarlinHubDashboard.svelte
  src/lib/page-components/oyster/dashboard/OysterDashboardPage.svelte
  src/lib/page-components/oyster/inventory/OysterInventoryHistoryTableRow.svelte
  src/lib/page-components/oyster/inventory/OysterInventoryTableRow.svelte
  src/lib/page-components/oyster/inventory/modals/WithdrawFundsFromJobModal.svelte
  src/lib/page-components/oyster/operator/OysterOperatorJobsTableRow.svelte
  src/lib/page-components/oyster/operator/OysterOperatorRegisterPage.svelte
  src/lib/page-components/oyster/operator/__snapshots__/OysterOperatorRegisterPage.spec.ts.snap
  src/routes/+layout.svelte
  tailwind.config.cjs
Labels: enhancement

#394 Fix bandwidth negative on stop
  src/lib/page-components/oyster/inventory/OysterInventoryExpandedTableRow.svelte
Labels: bug

#398 Gh action unit test coverage
  .github/workflows/test.yml
  package.json
  src/lib/utils/helpers/networkHelper.test.ts
Labels: enhancement

#400 updated the packages and their respective dependencies
  package-lock.json
  package.json
  src/lib/atoms/cards/__snapshots__/InputCard.dom.spec.ts.snap
  src/lib/atoms/divider/__snapshots__/Divider.dom.spec.ts.snap
  src/lib/atoms/icons/__snapshots__/Icon.dom.spec.ts.snap
  src/lib/atoms/modals/__snapshots__/Modal.dom.spec.ts.snap
  src/lib/atoms/table/__snapshots__/Table.dom.spec.ts.snap
  src/lib/atoms/texts/__snapshots__/Text.dom.spec.ts.snap
  src/lib/atoms/tooltips/__snapshots__/Tooltip.dom.spec.ts.snap
  src/lib/components/buttons/__snapshots__/buttons.dom.spec.ts.snap
  src/lib/components/cards/__snapshots__/ErrorTextCard.dom.spec.ts.snap
  src/lib/components/header/sub-components/__snapshots__/ChainSwitcher.dom.spec.ts.snap
  src/lib/components/header/sub-components/__snapshots__/DisconnectWalletButton.dom.spec.ts.snap
  src/lib/components/header/sub-components/__snapshots__/DisconnectWalletModal.dom.spec.ts.snap
  src/lib/components/header/sub-components/__snapshots__/HeaderConnectWallet.dom.spec.ts.snap
  src/lib/components/header/sub-components/__snapshots__/HeaderSubComponents.dom.spec.ts.snap
  src/lib/components/icons/__snapshots__/TxnIcon.dom.spec.ts.snap
  src/lib/components/inputs/__snapshots__/AmountInput.dom.spec.ts.snap
  src/lib/components/inputs/__snapshots__/AmountInputWithMaxButton.dom.spec.ts.snap
  src/lib/components/inputs/__snapshots__/AmountInputWithTitle.dom.spec.ts.snap
  src/lib/components/inputs/__snapshots__/InputCardWithEndButton.dom.spec.ts.snap
  src/lib/components/inputs/__snapshots__/TextInputWithEndButton.dom.spec.ts.snap
  src/lib/components/loading/__snapshots__/Loading.dom.spec.ts.snap
  src/lib/components/modals/__snapshots__/ApproveAndConfirmModal.dom.spec.ts.snap
  src/lib/components/modals/__snapshots__/Modal.dom.spec.ts.snap
  src/lib/components/prompts/__snapshots__/Prompts.dom.spec.ts.snap
  src/lib/components/search/__snapshots__/SearchBar.dom.spec.ts.snap
  src/lib/components/search/__snapshots__/SearchWithSelect.dom.spec.ts.snap
  src/lib/components/select/__snapshots__/Select.dom.spec.ts.snap
  src/lib/components/table-cells/__snapshots__/TableCells.dom.spec.ts.snap
  src/lib/components/texts/NameWithAddress.svelte
  src/lib/components/texts/__snapshots__/Texts.dom.spec.ts.snap
  src/lib/components/wrapper/__snapshots__/PageWrapper.dom.spec.ts.snap
  src/lib/page-components/oyster/operator/__snapshots__/OysterOperatorRegisterPage.spec.ts.snap
  svelte.config.js
  vite.config.ts
Labels: dependencies

#401 added unit tests to pre commit
  .husky/pre-commit
Labels: testing

#403 fixes for playwright test running before commit
  .husky/pre-commit
  package.json
  playwright.config.ts
  test/e2e/walletNotConnected/basic.spec.ts
  test/e2e/walletNotConnected/inventory.spec.ts
  test/e2e/walletNotConnected/marketplace.spec.ts
  test/helpers/marketplace.ts
Labels: enhancement

#404 add dark mode styles for mpond->pond conversion history cta
  src/lib/page-components/bridge/buttons/MPondConversionCycleButton.svelte
  src/lib/page-components/bridge/buttons/MPondConversionHistoryButton.svelte
  src/lib/page-components/bridge/history/MPondTableRow.svelte
Labels: bug

#405 fix kalypso dashboard showing when user has disconnected their wallet
  src/lib/page-components/kalypso/KalypsoDashboard.svelte
Labels: bug

#409 fix Address type declaration
  src/lib/controllers/contract/receiverRewards.ts
  src/lib/controllers/contract/token.ts
  src/lib/controllers/contract/usdc.ts
  src/lib/utils/helpers/contractHelpers.ts
  src/routes/bridge/mPondToPondHistory/+page.svelte
Labels: bug

#408 remove pond and mpond subgraphs entries from chain configs
  src/lib/chains/arbGoerli.ts
  src/lib/chains/arbOne.ts
  src/lib/chains/arbSepolia.ts
  src/lib/chains/ethereum.ts
  src/lib/chains/linea.ts
  src/lib/chains/lineaGoerli.ts
  src/lib/chains/polygon.ts
  src/lib/controllers/contract/receiverRewards.ts
  src/lib/controllers/contract/token.ts
  src/lib/controllers/contract/usdc.ts
  src/lib/types/environmentTypes.ts
  src/lib/utils/helpers/contractHelpers.ts
  src/routes/bridge/mPondToPondHistory/+page.svelte
Labels: refactor

#410 refactor unused stuff and updated docs
  src/lib/components/texts/NameWithAddress.svelte
  src/lib/components/texts/Texts.dom.spec.ts
  src/lib/controllers/README.md
  src/lib/controllers/subgraphController.ts
  src/lib/page-components/oyster/inventory/OysterInventoryHistoryTableRow.svelte
  src/lib/page-components/oyster/inventory/OysterInventoryPage.svelte
  src/lib/page-components/oyster/inventory/OysterInventoryTableRow.svelte
  src/lib/page-components/oyster/marketplace/OysterMarketplaceTableRow.svelte
  src/lib/page-components/oyster/operator/OysterOperatorJobs.svelte
  src/lib/page-components/oyster/operator/OysterOperatorJobsHistory.svelte
  src/lib/page-components/oyster/operator/OysterOperatorJobsHistoryTableRow.svelte
  src/lib/page-components/oyster/operator/OysterOperatorJobsTableRow.svelte
  src/lib/utils/constants/subgraphQueries.ts
Labels: refactor

#413 refactored and updated the theme switcher
  src/lib/atoms/ThemeSwitcher.svelte
  src/lib/components/header/sub-components/SidebarLinksGroup.svelte
  src/lib/components/sidebar/Sidebar.svelte
Labels: enhancement, refactor
