Repository marlinprotocol/interface-v2, pull requests merged in 2024-05, with the labels that each got.

#252 PR for minor oyster updates to new UI
  src/lib/components/v2/header/sub-components/SidebarLinksGroup.svelte
  src/lib/page-components/v2/oyster/marketplace/OysterMarketplaceTableRow.svelte
  src/lib/utils/constants/v2/oysterConstants.ts
Labels: enhancement

#256 PR to add back relay sidebar links and minor bugfix
  src/lib/components/v2/header/sub-components/SidebarLinksGroup.svelte
Labels: bug, enhancement

#255 PR to add in the main dashboard
  src/lib/atoms/v2/modals/ModalButton.svelte
  src/lib/components/v2/header/sub-components/SidebarLinksGroup.svelte
  src/lib/page-components/v2/dashboard/MarlinHubDashboard.svelte
  src/lib/types/v2/componentTypes.ts
  src/routes/v2/dashboard/+page.svelte
  src/routes/v2/oyster/+page.ts
Labels: bug, ui

#259 PR to add bugfixes for new UI
  src/lib/page-components/v2/oyster/inventory/OysterInventoryPage.svelte
  src/lib/page-components/v2/oyster/inventory/modals/WithdrawFundsFromJobModal.svelte
Labels: bug

#261 fix: operator page - input text not changing if user edits cp url
  src/lib/page-components/v2/oyster/operator/OysterOperatorRegisterPage.svelte
Labels: bug

#262 fix: added active chain on ecosystem
  src/lib/page-components/v2/ecosystem/EcosystemDashboard.svelte
  src/routes/v2/ecosystem/+layout.svelte
Labels: bug

#264 PR to upgrade ethers and minor styling fixes
  package-lock.json
  package.json
  src/lib/page-components/v2/oyster/inventory/OysterInventoryTableRow.svelte
  src/lib/page-components/v2/oyster/inventory/modals/CreateOrderModal.svelte
Labels: bug

#263 PR for adding oyster dashboard and fixes for spacing
  src/lib/components/images/staticImages.ts
  src/lib/components/v2/header/sub-components/SidebarLinksGroup.svelte
  src/lib/components/v2/wrapper/PageWrapper.svelte
  src/lib/page-components/v2/dashboard/MarlinHubDashboard.svelte
  src/lib/page-components/v2/ecosystem/EcosystemDashboard.svelte
  src/lib/page-components/v2/oyster/dashboard/OysterDashboardPage.svelte
  src/lib/types/headerTypes.ts
  src/lib/utils/constants/v2/urls.ts
  src/routes/v2/dashboard/+layout.svelte
  src/routes/v2/dashboard/+page.svelte
  src/routes/v2/oyster/+layout.svelte
  src/routes/v2/oyster/+page.svelte
  src/routes/v2/oyster/+page.ts
  src/routes/v2/oyster/inventory/+layout.svelte
  src/routes/v2/oyster/operator/jobs/+layout.svelte
  src/routes/v2/relay/+page.ts
  static/images/3dns.svg
  static/images/arrow-up-right.svg
  static/images/backend-servers.svg
  static/images/bonfida.svg
  static/images/chains.svg
  static/images/explore.svg
  static/images/frontends.svg
  static/images/instances.svg
  static/images/llms.svg
  static/images/regions.svg
  static/images/spaceid.svg
Labels: bug, ui

#267 fix: white color leak issue
  src/lib/components/v2/inputs/AmountInputWithTitle.svelte
  src/lib/components/v2/inputs/InputCardWithEndButton.svelte
  src/lib/components/v2/inputs/TextInputWithEndButton.svelte
  src/lib/components/v2/search/SearchWithSelect.svelte
  src/lib/page-components/v2/oyster/inventory/modals/CreateOrderModal.svelte
Labels: bug

#265 PR to update old routes with new UI
  src/lib/utils/constants/v2/urls.ts
  src/routes/+error.svelte
  src/routes/+layout.svelte
  src/routes/+page.ts
  src/routes/bridge/+layout.svelte
  src/routes/bridge/+page.svelte
  src/routes/bridge/mPondToPondHistory/+page.svelte
  src/routes/bridge/pondToMPondHistory/+page.svelte
  src/routes/dashboard/+layout.svelte
  src/routes/dashboard/+page.svelte
  src/routes/ecosystem/+layout.svelte
  src/routes/ecosystem/+page.svelte
  src/routes/kalypso/+page.svelte
  src/routes/oyster/+layout.svelte
  src/routes/oyster/+page.svelte
  src/routes/oyster/+page.ts
  src/routes/oyster/inventory/+layout.svelte
  src/routes/oyster/inventory/+page.svelte
  src/routes/oyster/inventory/history/+page.svelte
  src/routes/oyster/marketplace/+page.svelte
  src/routes/oyster/operator/+layout.svelte
  src/routes/oyster/operator/+page.svelte
  src/routes/oyster/operator/+page.ts
  src/routes/oyster/operator/jobs/+layout.svelte
  src/routes/oyster/operator/jobs/+page.svelte
  src/routes/oyster/operator/jobs/history/+page.svelte
  src/routes/relay/+layout.svelte
  src/routes/relay/+page.ts
  src/routes/relay/receiver/+page.ts
  src/routes/relay/receiver/rewards/+page.svelte
  src/routes/relay/receiver/staking/+page.svelte
  src/routes/v2/+error.svelte
  src/routes/v2/+layout.svelte
  src/routes/v2/+layout.ts
  src/routes/v2/+page.ts
  src/routes/v2/README.md
  src/routes/v2/bridge/+layout.svelte
  src/routes/v2/bridge/+page.svelte
  src/routes/v2/bridge/mPondToPondHistory/+page.svelte
  src/routes/v2/bridge/pondToMPondHistory/+page.svelte
  src/routes/v2/oyster/+layout.svelte
  src/routes/v2/oyster/inventory/+layout.svelte
  src/routes/v2/oyster/inventory/+page.svelte
  src/routes/v2/oyster/inventory/history/+page.svelte
  src/routes/v2/oyster/marketplace/+page.svelte
  src/routes/v2/oyster/operator/jobs/+layout.svelte
  src/routes/v2/oyster/operator/jobs/+page.svelte
  src/routes/v2/oyster/operator/jobs/history/+page.svelte
  src/routes/v2/relay/+layout.svelte
  src/routes/v2/relay/receiver/+page.ts
  src/routes/v2/relay/receiver/rewards/+page.svelte
  src/routes/v2/relay/receiver/staking/+page.svelte
Labels: ui

#269 Bug Fixes
  src/lib/components/v2/inputs/AmountInputWithMaxButton.svelte
  src/lib/components/v2/inputs/AmountInputWithTitle.svelte
  src/lib/components/v2/inputs/InputCardWithEndButton.svelte
  src/lib/components/v2/inputs/TextInputWithEndButton.svelte
  src/lib/components/v2/texts/NameWithAddress.svelte
  src/lib/components/v2/texts/TextInputCard.svelte
  src/lib/page-components/v2/oyster/inventory/OysterInventoryHistoryPage.svelte
  src/lib/page-components/v2/oyster/inventory/OysterInventoryTableRow.svelte
  src/lib/page-components/v2/oyster/inventory/modals/JobDetailsModal.svelte
  src/lib/page-components/v2/oyster/inventory/modals/PastJobDetailsModal.svelte
  src/lib/page-components/v2/oyster/marketplace/OysterMarketplaceTableRow.svelte
  src/lib/page-components/v2/oyster/operator/OysterOperatorRegisterPage.svelte
  src/lib/page-components/v2/oyster/sub-components/MetadetailsForNewOrder.svelte
  src/lib/page-components/v2/oyster/sub-components/StopModalContent.svelte
  src/lib/utils/v2/helpers/componentHelper.ts
  static/images/clockIcon.svg
  static/images/walletIconOyster.svg
Labels: bug

#268 PR to reordee partners section and minor tweaks
  src/lib/components/v2/modals/ExternalLinkConfirmationModal.svelte
  src/lib/page-components/v2/oyster/dashboard/OysterDashboardPage.svelte
Labels: ui

#270 PR to add bugfixes for new UI
  src/lib/components/images/staticImages.ts
  src/lib/components/v2/header/sub-components/DisconnectWalletModal.svelte
  src/lib/components/v2/inputs/AmountInput.svelte
  src/lib/components/v2/inputs/AmountInputWithTitle.svelte
  src/lib/components/v2/inputs/TextInputWithEndButton.svelte
  src/lib/components/v2/prompts/NetworkPrompt.svelte
  src/lib/components/v2/sidebar/Sidebar.svelte
  src/lib/components/v2/texts/TableHeadingText.svelte
  src/lib/components/v2/texts/TextInputCard.svelte
  src/lib/page-components/oyster/marketplace/OysterMarketplacePage.svelte
  src/lib/page-components/v2/dashboard/MarlinHubDashboard.svelte
  src/lib/page-components/v2/oyster/inventory/OysterInventoryHistoryTableRow.svelte
  src/lib/page-components/v2/oyster/inventory/OysterInventoryTableRow.svelte
  src/lib/page-components/v2/oyster/inventory/modals/AmendRateModal.svelte
  src/lib/page-components/v2/oyster/inventory/modals/CreateOrderModal.svelte
  src/lib/page-components/v2/oyster/inventory/modals/JobDetailsModal.svelte
  src/lib/page-components/v2/oyster/marketplace/OysterMarketplaceTableRow.svelte
  src/lib/page-components/v2/oyster/operator/Modals/RegisterModal.svelte
  src/lib/page-components/v2/oyster/operator/OysterOperatorJobsHistoryTableRow.svelte
  src/lib/page-components/v2/oyster/operator/OysterOperatorJobsTableRow.svelte
  src/lib/page-components/v2/oyster/sub-components/AddFundsToJob.svelte
  src/lib/page-components/v2/oyster/sub-components/BandwidthSelector.svelte
  src/lib/types/v2/componentTypes.ts
  src/lib/utils/constants/v2/urls.ts
  src/routes/bridge/+layout.svelte
  src/routes/oyster/+layout.svelte
  src/routes/oyster/operator/+layout.svelte
  src/routes/oyster/operator/+page.svelte
  src/routes/oyster/operator/+page.ts
  src/routes/oyster/operator/history/+page.svelte
  src/routes/oyster/operator/jobs/+layout.svelte
  static/images/copyIconNew.svg
  static/images/information-purple.svg
Labels: bug, enhancement, ui

#275 PR to refactor urls into external and routes
  src/lib/components/v2/header/sub-components/SidebarLinksGroup.svelte
  src/lib/page-components/v2/dashboard/MarlinHubDashboard.svelte
  src/lib/page-components/v2/oyster/dashboard/OysterDashboardPage.svelte
  src/lib/types/headerTypes.ts
  src/lib/utils/constants/v2/navigation.ts
  src/lib/utils/constants/v2/urls.ts
Labels: refactor

#276 Create Order Details fixes
  src/lib/components/cards/ErrorTextCard.svelte
  src/lib/page-components/v2/oyster/inventory/modals/CreateOrderModal.svelte
  src/lib/page-components/v2/oyster/sub-components/BandwidthSelector.svelte
  src/lib/page-components/v2/oyster/sub-components/MetadetailsForNewOrder.svelte
Labels: bug

#278 fix: added ecosys logoes
  src/lib/components/images/staticImages.ts
  src/lib/page-components/v2/ecosystem/EcosystemDashboard.svelte
  static/images/AspectaLogo.png
  static/images/AspectaLogo.webp
  static/images/Avail-Logo-OnDark.3bbffcbf.png
  static/images/Brightlystakelogo.png
  static/images/Brightlystakelogo.webp
  static/images/ChorusOneLogo.png
  static/images/ChorusOneLogo.webp
  static/images/CradlesLogo.webp
  static/images/DegoFinance.png
  static/images/DegoFinance.webp
  static/images/EcholinkLogo.png
  static/images/EcholinkLogo.webp
  static/images/FlashBotsLogo.webp
  static/images/GoSleepLogo.png
  static/images/GoSleepLogo.webp
  static/images/HashkeyCloudLogo.webp
  static/images/InfstonesLogo.png
  static/images/InfstonesLogo.webp
  static/images/MidaswapLogo.png
  static/images/MidaswapLogo.webp
  static/images/NodeEasyLogo.png
  static/images/NodeEasyLogo.webp
  static/images/PublicAIDarkLogo.png
  static/images/PublicAIDarkLogo.webp
  static/images/ShanghaiJiaoTongUniversityLogo.png
  static/images/StafiLogo.png
  static/images/StafiLogo.webp
  static/images/Staking4AllLogo.png
  static/images/Staking4AllLogo.webp
  static/images/ankr-blue-logo.png
  static/images/ankr-blue-logo.webp
  static/images/availLogo.webp
  static/images/decimal.webp
  static/images/gearbox.webp
  static/images/injective.webp
  static/images/mellow.webp
  static/images/operator.svg
  static/images/p2p_logo_white.png
  static/images/p2p_logo_white.webp
  static/images/polygon-full.webp
  static/images/side.svg
  static/images/sjtUni.webp
  static/images/zkbob.svg
Labels: enhancement

#280 PR to fix overflow and sort logos alphabetically
  src/lib/page-components/v2/ecosystem/EcosystemDashboard.svelte
Labels: bug

#282 fix: closed -> stopped
  src/lib/page-components/v2/oyster/inventory/OysterInventoryHistoryPage.svelte
  src/lib/utils/data-modifiers/oysterModifiers.ts
Labels: bug

#284 fix: copy fix
  src/lib/page-components/v2/bridge/MPondTopond.svelte
Labels: bug

#286 PR to add oyster operator fixes
  src/lib/atoms/divider/Divider.svelte
  src/lib/atoms/table/Table.svelte
  src/lib/page-components/oyster/inventory/OysterTableCommon.svelte
  src/lib/page-components/oyster/operator/Modals/RegisterModal.svelte
  src/lib/page-components/oyster/operator/OysterOperatorRegisterPage.svelte
Labels: bug, ui

#290 fix: closed -> stopped
  src/lib/page-components/oyster/inventory/OysterInventoryPage.svelte
  src/lib/page-components/oyster/operator/OysterOperatorJobs.svelte
  src/lib/page-components/oyster/operator/OysterOperatorJobsHistory.svelte
  src/lib/types/oysterComponentType.ts
  src/lib/utils/helpers/oysterHelpers.ts
Labels: bug, enhancement

#289 PR to add some UI tweaks
  src/lib/components/inputs/AmountInputWithTitle.svelte
  src/lib/page-components/bridge/MPondTopond.svelte
  src/lib/page-components/bridge/PondToMPond.svelte
  src/lib/page-components/dashboard/MarlinHubDashboard.svelte
  src/lib/page-components/oyster/dashboard/OysterDashboardPage.svelte
Labels: ui

#291 fix: error issue while instance & region
  src/lib/page-components/oyster/sub-components/MetadetailsForNewOrder.svelte
Labels: bug

#292 fix: added missed logo
  src/lib/components/images/staticImages.ts
  src/lib/page-components/ecosystem/EcosystemDashboard.svelte
  static/images/arbitrum-full.webp
  static/images/limo.webp
  static/images/mcgill-university.webp
  static/images/sigmoid.svg
Labels: enhancement

#293 filters updated
  src/lib/page-components/oyster/marketplace/OysterMarketplaceFilters.svelte
  src/lib/utils/helpers/oysterHelpers.ts
Labels: bug, enhancement

#296 PR for updating the coming soon page for kalypso
  src/lib/components/images/staticImages.ts
  src/lib/page-components/kalypso/KalypsoDashboard.svelte
  src/routes/+error.svelte
  src/routes/kalypso/+page.svelte
  static/images/fishing-man.svg
Labels: ui

#297 PR to update dashboard links and metadata
  src/lib/page-components/oyster/dashboard/OysterDashboardPage.svelte
Labels: enhancement

#298 fix: added new cat & logo
  src/app.css
  src/lib/components/images/staticImages.ts
  src/lib/page-components/ecosystem/EcosystemDashboard.svelte
  static/images/Kontos.svg
  static/images/NuLink.svg
  static/images/lighthouse.svg
Labels: enhancement

#299 copy fix
  src/lib/page-components/kalypso/KalypsoDashboard.svelte
Labels: bug

#300 Oyster operator input bugfix
  src/lib/page-components/oyster/operator/Modals/RegisterModal.svelte
Labels: bug

#303 fix: model overflow issue
  src/app.css
  src/lib/atoms/modals/Modal.svelte
Labels: bug

#308 fix: added svgs of eco sys
  src/lib/components/images/staticImages.ts
  src/lib/page-components/ecosystem/EcosystemDashboard.svelte
  static/images/AspectaLogo.svg
  static/images/AspectaLogo.webp
  static/images/ChorusOneLogo.svg
  static/images/ChorusOneLogo.webp
  static/images/EcholinkLogo.svg
  static/images/EcholinkLogo.webp
  static/images/FlashBotsLogo.svg
  static/images/FlashBotsLogo.webp
  static/images/GoSleepLogo.svg
  static/images/GoSleepLogo.webp
  static/images/HashkeyCloudLogo.png
  static/images/HashkeyCloudLogo.svg
  static/images/HashkeyCloudLogo.webp
  static/images/InfstonesLogo.svg
  static/images/InfstonesLogo.webp
  static/images/MidaswapLogo.svg
  static/images/MidaswapLogo.webp
  static/images/StafiLogo.svg
  static/images/StafiLogo.webp
  static/images/ankr-blue-logo.svg
  static/images/ankr-blue-logo.webp
  static/images/arbitrum-full.svg
  static/images/arbitrum-full.webp
  static/images/availLogo.svg
  static/images/availLogo.webp
  static/images/gearbox.svg
  static/images/gearbox.webp
  static/images/injective.svg
  static/images/injective.webp
  static/images/mcgill-university.svg
  static/images/mcgill-university.webp
  static/images/p2p_logo.svg
  static/images/p2p_logo.webp
  static/images/polygon-full.svg
  static/images/polygon-full.webp
Labels: enhancement

#307 cleanup unused svelte files
  package-lock.json
  package.json
  src/lib/atoms/buttons/InfoButtonLink.svelte
  src/lib/atoms/buttons/TestButton.svelte
  src/lib/atoms/images/ImageColored.svelte
  src/lib/atoms/tabs/TabList.svelte
  src/lib/atoms/tabs/TabPanel.svelte
  src/lib/atoms/tabs/Tabs.svelte
  src/lib/components/header/sub-components/HeaderLogo.svelte
  src/lib/components/header/sub-components/WalletCard.svelte
  src/lib/components/loading/LoadingAnimationModal.svelte
  src/lib/components/search/Country.svelte
  src/lib/components/table-cells/TableDataCell.svelte
  src/lib/page-components/bridge/sub-components/HistoryBackButton.svelte
  src/lib/page-components/bridge/sub-components/HistoryDataIconButton.svelte
  src/lib/page-components/oyster/inventory/modals/UpdateEnclaveUrlModal.svelte
  src/lib/page-components/oyster/marketplace/TableFilter.svelte
  src/lib/page-components/oyster/sub-components/InstancesTable.svelte
Labels: refactor

#309 fix tabs component deletion
  src/lib/atoms/tabs/TabList.svelte
  src/lib/atoms/tabs/TabPanel.svelte
  src/lib/atoms/tabs/Tabs.svelte
Labels: bug

#312 swap text arrow with icon in dashboard
  src/lib/page-components/dashboard/MarlinHubDashboard.svelte
  src/lib/types/componentTypes.ts
Labels: enhancement

#311 test: improved test cases
  src/lib/atoms/buttons/Button.dom.spec.ts
  src/lib/atoms/buttons/__snapshots__/Button.dom.spec.ts.snap
  src/lib/atoms/cards/InputCard.dom.spec.ts
  src/lib/atoms/cards/__snapshots__/InputCard.dom.spec.ts.snap
  src/lib/atoms/divider/__snapshots__/Divider.dom.spec.ts.snap
  src/lib/atoms/modals/Modal.dom.spec.ts
  src/lib/atoms/modals/__snapshots__/Modal.dom.spec.ts.snap
  src/lib/atoms/table/Table.dom.spec.ts
  src/lib/atoms/table/__snapshots__/Table.dom.spec.ts.snap
  src/lib/atoms/tabs/Tabs.dom.spec.ts
  src/lib/atoms/tabs/__snapshots__/Tabs.dom.spec.ts.snap
  src/lib/atoms/tooltips/Tooltip.dom.spec.ts
  src/lib/atoms/tooltips/__snapshots__/Tooltip.dom.spec.ts.snap
  src/lib/components/buttons/__snapshots__/buttons.dom.spec.ts.snap
  src/lib/components/buttons/buttons.dom.spec.ts
  src/lib/components/cards/__snapshots__/ErrorTextCard.dom.spec.ts.snap
  src/lib/components/header/sub-components/__snapshots__/ChainSwitcher.dom.spec.ts.snap
  src/lib/components/header/sub-components/__snapshots__/DisconnectWalletButton.dom.spec.ts.snap
  src/lib/components/header/sub-components/__snapshots__/DisconnectWalletModal.dom.spec.ts.snap
  src/lib/components/header/sub-components/__snapshots__/HeaderConnectWallet.dom.spec.ts.snap
  src/lib/components/header/sub-components/__snapshots__/HeaderSubComponents.dom.spec.ts.snap
  src/lib/components/inputs/AmountInput.dom.spec.ts
  src/lib/components/inputs/__snapshots__/AmountInput.dom.spec.ts.snap
  src/lib/components/inputs/__snapshots__/AmountInputWithMaxButton.dom.spec.ts.snap
  src/lib/components/inputs/__snapshots__/AmountInputWithTitle.dom.spec.ts.snap
  src/lib/components/inputs/__snapshots__/InputCardWithEndButton.dom.spec.ts.snap
  src/lib/components/inputs/__snapshots__/TextInputWithEndButton.dom.spec.ts.snap
  src/lib/components/modals/Modal.dom.spec.ts
  src/lib/components/modals/__snapshots__/ApproveAndConfirmModal.dom.spec.ts.snap
  src/lib/components/modals/__snapshots__/Modal.dom.spec.ts.snap
  src/lib/components/prompts/__snapshots__/Prompts.dom.spec.ts.snap
  src/lib/components/search/__snapshots__/SearchBar.dom.spec.ts.snap
  src/lib/components/search/__snapshots__/SearchWithSelect.dom.spec.ts.snap
  src/lib/components/select/Select.dom.spec.ts
  src/lib/components/select/__snapshots__/Select.dom.spec.ts.snap
  src/lib/components/table-cells/__snapshots__/TableCells.dom.spec.ts.snap
  src/lib/components/texts/TextInputCard.svelte
  src/lib/components/texts/Texts.dom.spec.ts
  src/lib/components/texts/__snapshots__/Texts.dom.spec.ts.snap
  src/lib/components/wrapper/__snapshots__/PageWrapper.dom.spec.ts.snap
  src/lib/utils/helpers/conversionHelper.test.ts
  src/lib/utils/helpers/oysterHelper.test.ts
Labels: enhancement, testing, refactor

#315 Marketplace filters integration tests fix
  test/e2e/walletNotConnected/marketplace.spec.ts
Labels: testing

#317 add accseal logo
  src/lib/components/images/staticImages.ts
  src/lib/page-components/ecosystem/EcosystemDashboard.svelte
  static/images/accsealLogo.svg
Labels: enhancement

#316 fix: Unit test cases
  src/lib/atoms/buttons/Button.dom.spec.ts
  src/lib/atoms/buttons/InfoButtonLink.dom.spec.ts
  src/lib/atoms/images/Image.dom.spec.ts
  src/lib/atoms/images/__snapshots__/Image.dom.spec.ts.snap
  src/lib/components/header/sub-components/ChainSwitcher.dom.spec.ts
  src/lib/components/header/sub-components/DisconnectWalletButton.dom.spec.ts
  src/lib/components/header/sub-components/DisconnectWalletModal.dom.spec.ts
  src/lib/components/header/sub-components/HeaderSubComponents.dom.spec.ts
  src/lib/components/inputs/AmountInputWithMaxButton.dom.spec.ts
  src/lib/components/inputs/AmountInputWithTitle.dom.spec.ts
  src/lib/components/loading/Loading.dom.spec.ts
  src/lib/components/loading/__snapshots__/Loading.dom.spec.ts.snap
  src/lib/components/search/Country.dom.spec.ts
  src/lib/components/table-cells/TableCells.dom.spec.ts
  src/lib/utils/helpers/httpHelper.test.ts
Labels: enhancement, testing

#318 fix: enclave input ui
  src/lib/page-components/oyster/inventory/modals/CreateOrderModal.svelte
Labels: bug, enhancement

#320 fix: Unit test cases
  src/lib/components/header/sub-components/ChainSwitcher.dom.spec.ts
  src/lib/components/header/sub-components/DisconnectWalletButton.dom.spec.ts
  src/lib/components/header/sub-components/__snapshots__/ChainSwitcher.dom.spec.ts.snap
  src/lib/components/header/sub-components/__snapshots__/DisconnectWalletButton.dom.spec.ts.snap
  src/lib/components/header/sub-components/__snapshots__/HeaderConnectWallet.dom.spec.ts.snap
  src/lib/components/header/sub-components/__snapshots__/HeaderSubComponents.dom.spec.ts.snap
  src/lib/components/prompts/__snapshots__/Prompts.dom.spec.ts.snap
Labels: enhancement, testing

#321 fix: added new Favicon
  src/app.html
  static/favicon.ico
  static/favicon.png
Labels: bug, enhancement

#323 fix: resolved failed UTs
  src/lib/data-stores/mock-data-stores/mockStores.ts
  src/lib/page-components/oyster/operator/OysterOperatorRegisterPage.spec.ts
  src/lib/page-components/oyster/operator/__snapshots__/OysterOperatorRegisterPage.spec.ts.snap
  src/lib/utils/helpers/conversionHelper.test.ts
  src/lib/utils/helpers/conversionHelper.ts
Labels: enhancement, testing

#326 fix: table center as per prop.
  src/lib/atoms/table/Table.svelte
  src/lib/components/texts/NameWithAddress.svelte
  src/lib/components/texts/TableHeadingText.svelte
  src/lib/page-components/oyster/marketplace/OysterMarketplaceTableRow.svelte
  src/lib/utils/constants/oysterConstants.ts
Labels: enhancement, ui

#324 fix: CP URL err conditions issue
  src/lib/page-components/oyster/operator/Modals/RegisterModal.svelte
Labels: bug, enhancement

#331 fix: ip text upper case
  src/lib/utils/constants/oysterConstants.ts
Labels: enhancement

#330 fix: added Filecoin Foundation logo
  src/lib/components/images/staticImages.ts
  src/lib/page-components/ecosystem/EcosystemDashboard.svelte
  static/images/fil.svg
Labels: ui

#333 fix: added talus logo
  src/lib/components/images/staticImages.ts
  src/lib/page-components/ecosystem/EcosystemDashboard.svelte
  static/images/talus.svg
Labels: ui

#332 Operator wallet not connected table state
  src/lib/components/images/staticImages.ts
  src/lib/components/prompts/NetworkPrompt.svelte
  src/lib/components/prompts/Prompts.dom.spec.ts
  src/lib/components/prompts/__snapshots__/Prompts.dom.spec.ts.snap
  src/lib/page-components/bridge/history/HistoryTableCommon.svelte
  src/lib/page-components/oyster/inventory/OysterInventoryHistoryPage.svelte
  src/lib/page-components/oyster/inventory/OysterInventoryPage.svelte
  src/lib/page-components/oyster/inventory/OysterTableCommon.svelte
  src/lib/page-components/oyster/operator/OysterOperatorJobs.svelte
  src/lib/page-components/oyster/operator/OysterOperatorJobsHistory.svelte
  src/routes/bridge/+layout.svelte
  src/routes/oyster/+layout.svelte
  static/images/information-white.svg
Labels: bug

#334 Empty state fix
  src/lib/components/empty-state/EmptyCard.svelte
  src/lib/page-components/kalypso/KalypsoDashboard.svelte
  src/lib/page-components/oyster/inventory/OysterTableCommon.svelte
  src/lib/page-components/oyster/operator/OysterOperatorJobs.svelte
  src/lib/page-components/oyster/operator/OysterOperatorJobsHistory.svelte
Labels: enhancement

#335 fix: removed certain logo
  src/lib/atoms/timer/Timer.dom.spec.ts
  src/lib/page-components/ecosystem/EcosystemDashboard.svelte
Labels: enhancement

#336 hub and oyster bugfixes
  src/lib/components/header/sub-components/SidebarLinksGroup.svelte
  src/lib/page-components/dashboard/MarlinHubDashboard.svelte
  src/lib/page-components/oyster/inventory/OysterInventoryHistoryTableRow.svelte
  src/lib/page-components/oyster/inventory/OysterInventoryTableRow.svelte
  src/lib/page-components/oyster/sub-components/PaymentHistoryTable.svelte
  src/lib/types/componentTypes.ts
  src/lib/types/headerTypes.ts
  src/lib/utils/constants/constants.ts
Labels: bug, enhancement, ui

#295 feat: Change Bandwidth
  src/lib/atoms/toast/Toast.svelte
  src/lib/components/search/__snapshots__/SearchWithSelect.dom.spec.ts.snap
  src/lib/components/select/Select.svelte
  src/lib/components/select/__snapshots__/Select.dom.spec.ts.snap
  src/lib/controllers/contract/oyster.ts
  src/lib/controllers/contract/oysterCredit.ts
  src/lib/data-stores/oysterStore.ts
  src/lib/data-stores/toastStore.ts
  src/lib/page-components/bridge/history/MPondToPondHistoryData.svelte
  src/lib/page-components/oyster/inventory/OysterInventoryExpandedTableRow.svelte
  src/lib/page-components/oyster/inventory/OysterInventoryTableRow.svelte
  src/lib/page-components/oyster/inventory/modals/AmendRateModal.svelte
  src/lib/page-components/oyster/inventory/modals/ChangeBandwidthModal.svelte
  src/lib/page-components/oyster/inventory/modals/CreateOrderModal.svelte
  src/lib/page-components/oyster/inventory/modals/JobDetailsModal.svelte
  src/lib/page-components/oyster/inventory/modals/StopJobModal.svelte
  src/lib/types/componentTypes.ts
  src/lib/types/oysterComponentType.ts
  src/lib/utils/constants/messages.ts
  src/lib/utils/constants/oysterConstants.ts
  src/lib/utils/data-modifiers/oysterModifiers.ts
  src/lib/utils/helpers/contractHelpers.ts
  src/lib/utils/helpers/conversionHelper.ts
  src/lib/utils/helpers/oysterHelpers.ts
  src/lib/utils/services/oysterServices.ts
Labels: enhancement

#341 Souvik/remove daisyui logs
  src/routes/+layout.svelte
  tailwind.config.cjs
Labels: refactor

#345 fix: order deployments latest first
  src/routes/oyster/inventory/+layout.svelte
Labels: bug

#344 ip input overflow fix
  src/lib/page-components/oyster/inventory/modals/JobDetailsModal.svelte
Labels: bug

#342 Fix/ecosystem copy fixes
  src/lib/page-components/ecosystem/EcosystemDashboard.svelte
Labels: bug

#343 open learn more links in new tab
  src/lib/page-components/dashboard/MarlinHubDashboard.svelte
  src/lib/types/componentTypes.ts
Labels: bug

#346 fix: move completed jobs when claimed to history tab
  src/lib/data-stores/oysterStore.ts
Labels: bug

#349 fix navigation
  src/lib/page-components/dashboard/MarlinHubDashboard.svelte
Labels: bug

#340 Chain switcher dropdown
  src/lib/components/header/sub-components/ChainSwitcher.svelte
  src/lib/components/header/sub-components/ConnectWalletButton.svelte
  src/lib/components/header/sub-components/HeaderConnectWallet.svelte
  src/lib/components/header/sub-components/__snapshots__/HeaderConnectWallet.dom.spec.ts.snap
  src/lib/components/prompts/NetworkPrompt.svelte
  src/lib/components/prompts/Prompts.dom.spec.ts
  src/lib/components/prompts/__snapshots__/Prompts.dom.spec.ts.snap
  src/lib/components/texts/PageTitle.svelte
  src/lib/page-components/bridge/history/HistoryTableCommon.svelte
  src/lib/page-components/bridge/history/MPondToPondHistoryData.svelte
  src/lib/page-components/bridge/history/PondToMPondHistoryData.svelte
  src/lib/page-components/oyster/inventory/OysterTableCommon.svelte
  src/routes/bridge/+layout.svelte
  src/routes/oyster/+layout.svelte
Labels: bug, enhancement

#350 fix: animation and icon change
  src/lib/page-components/bridge/history/HistoryTableCommon.svelte
Labels: enhancement

#348 text wrap for conversion modal.
  src/lib/components/modals/__snapshots__/ApproveAndConfirmModal.dom.spec.ts.snap
  src/lib/components/modals/__snapshots__/Modal.dom.spec.ts.snap
  src/lib/page-components/bridge/modals/SuccessfulConversionModal.svelte
Labels: bug, enhancement

#351 Claim Job Toast fix
  src/lib/controllers/contract/oyster.ts
  src/lib/controllers/contract/oysterCredit.ts
  src/lib/utils/constants/messages.ts
Labels: bug

#352 create order moda and redeploy bandwidth calculation fixes
  src/lib/page-components/oyster/inventory/OysterInventoryHistoryTableRow.svelte
  src/lib/page-components/oyster/inventory/modals/CreateOrderModal.svelte
  src/lib/page-components/oyster/sub-components/AddFundsToJob.svelte
  src/lib/page-components/oyster/sub-components/MetadetailsForNewOrder.svelte
Labels: bug

#353 commented out enclave image inputs
  src/lib/page-components/oyster/inventory/modals/CreateOrderModal.svelte
Labels: refactor

#361 create order modal disable first 3 inputs
  src/lib/components/search/SearchWithSelect.svelte
  src/lib/page-components/oyster/sub-components/MetadetailsForNewOrder.svelte
Labels: enhancement

#362 Create order modal cost fix
  src/lib/page-components/oyster/sub-components/BandwidthSelector.svelte
Labels: bug

#357 added job name to job metadata
  src/lib/atoms/tooltips/Tooltip.svelte
  src/lib/components/inputs/InputCardWithEndButton.svelte
  src/lib/components/inputs/TextInputWithEndButton.svelte
  src/lib/components/texts/NameWithAddress.svelte
  src/lib/page-components/oyster/inventory/OysterInventoryHistoryPage.svelte
  src/lib/page-components/oyster/inventory/OysterInventoryHistoryTableRow.svelte
  src/lib/page-components/oyster/inventory/OysterInventoryPage.svelte
  src/lib/page-components/oyster/inventory/OysterInventoryTableRow.svelte
  src/lib/page-components/oyster/inventory/modals/CreateOrderModal.svelte
  src/lib/page-components/oyster/inventory/modals/JobDetailsModal.svelte
  src/lib/page-components/oyster/inventory/modals/PastJobDetailsModal.svelte
  src/lib/page-components/oyster/operator/__snapshots__/OysterOperatorRegisterPage.spec.ts.snap
  src/lib/types/oysterComponentType.ts
  src/lib/utils/constants/oysterConstants.ts
  src/lib/utils/data-modifiers/oysterModifiers.ts
  src/lib/utils/helpers/oysterHelper.test.ts
  src/lib/utils/helpers/oysterHelpers.ts
  src/routes/+layout.svelte
Labels: enhancement

#364 fix: added heurist & Assisterr logo
  src/lib/components/images/staticImages.ts
  src/lib/page-components/ecosystem/EcosystemDashboard.svelte
  static/images/assisterr.svg
  static/images/heurist.svg
Labels: enhancement

#360 fix: token for getAllowances
  src/routes/bridge/+layout.svelte
  src/routes/oyster/+layout.svelte
Labels: enhancement
